name: 🔨 Build Test

on:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: "Lint"
    if: "${{ !endsWith(github.actor, '[bot]') }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: projectdiscovery/actions/setup/go@v1
      - uses: projectdiscovery/actions/golangci-lint@v1

  build:
    name: Test Builds
    needs: ["lint"]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: projectdiscovery/actions/setup/go@v1

      - name: Test
        run: go test ./...

      - name: Race Condition Tests
        if: ${{ matrix.os != 'windows-latest' }} # false positives in windows
        run: go test -race ./...

      - name: Fuzz File Read  # fuzz tests need to be run separately  
        run:  go test -fuzztime=10s -fuzz=FuzzSafeOpen -run "FuzzSafeOpen" ./file/...
