name: ⏫ Bump Version

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: projectdiscovery/actions/setup/git@v1
      - uses: projectdiscovery/actions/svu-next@v1
        with:
          v0: true
          release-create: true
