name: 🔨 Build Test

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Test Builds
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.x

      - name: Check out code
        uses: actions/checkout@v3

      - name: Detach Mode  # detach tests needs an independent parent process  
        run:  ./detach/tests/test.sh
